# Experiment
experiment_name: debug

# Data from preprocessing
max_len: 5000 # maximum number of images to load
validation_ratio: 0.002 # this will get a set of random images by default

# Network to be used by the CM [diffusers, homemade, udffdb, conditional, heavy_diffusers]
network: diffusers
main_variables: [precip]
conditional_variables: # [hours, months]

# Network configuration
dropout: 0.3

# Loss weighting
loss_weight: True # whether or nor to use the lambda schedule

# Optimizer
optimizer: radam

# Hyperparameters
learning_rate: 1e-6
batch_size: 1
sigma_min: 0.002
sigma_max: 80.0
epochs: 100
ema_decay_rate: 0.999

# Normalizations
log_transform: True
norm_mean: 0.0
norm_std: 2.0

# Logging and checkpointing
log_each: 5000
checkpoint_each: 2 # checkpoint each #number of epochs
